# Generated by Django 3.0.8 on 2020-07-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
    ]
