# Generated by Django 3.0.8 on 2020-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200721_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysubcategory',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
