# Generated by Django 3.0.8 on 2020-07-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_categorysubcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubcategory',
            name='name',
        ),
    ]
