# Generated by Django 3.0.8 on 2020-07-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_categorysubcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialorder',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
