# Generated by Django 3.0.8 on 2020-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200723_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
