# Generated by Django 3.0.8 on 2020-07-24 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0009_auto_20200723_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'order_status',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.CharField(max_length=250)),
                ('time_paid', models.DateTimeField(null=True)),
                ('time_canceled', models.DateTimeField(null=True)),
                ('time_completed', models.DateTimeField(null=True)),
                ('time_snet', models.DateTimeField(null=True)),
                ('time_delivered', models.DateTimeField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=False)),
                ('order_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.OrderStatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'db_table': 'users_orders',
            },
        ),
        migrations.RemoveField(
            model_name='productgood',
            name='good',
        ),
        migrations.RemoveField(
            model_name='productgood',
            name='product',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='ProductGood',
        ),
    ]
