# Generated by Django 3.0.8 on 2020-07-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_likeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
