# Generated by Django 3.0.8 on 2020-07-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.AddField(
            model_name='specialorder',
            name='detail_image',
            field=models.URLField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialorder',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='specialorder',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterModelTable(
            name='specialorder',
            table='special_orders',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
