# Generated by Django 3.0.8 on 2020-07-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200727_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
