# Generated by Django 3.0.8 on 2020-07-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_img',
            new_name='thumbnail_image',
        ),
        migrations.RenameField(
            model_name='posthashtag',
            old_name='hashtags',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='posthashtag',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='official',
            new_name='is_official',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='logo',
            new_name='logo_url',
        ),
    ]
