# Generated by Django 3.0.8 on 2020-07-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200727_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
