# Generated by Django 3.0.8 on 2020-07-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delivery'),
        ('cart', '0004_remove_orderproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='userorder',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Delivery'),
        ),
    ]
